travis:
  secure:
    BINSTAR_TOKEN: gbSpty9ZJPX6HLmiuNoLQkkCWir03PGQ36G5BHxd9SEXCPeK86pOgijbcnjrI8w176E7slG4muTdUsoXA7w24ZmaRIMMC4NK8p1ElerLof/RjlNwYhT7xlnDGtMwjkqShB/2JLgaLQb0tBTTazkRszdBD9lgHr64nuInWEELdNcYMCnVxk9Ov9POxVcNnlqfLy6Gd7JfydInEoSWwIu5bgyxJ/61Z8tI64/9xgkk98O8gWTZSEndzMOtohyM/gr0vAFhbS945WqQ4pBiET6td1dDFtIqOjHgqQBfxVY8qoMUb7dUvQxDYUsgqdCP5UUYdJBE4+wuWxLMS7cnwtisWAcsVXmE+R1R/pSOho8hiLfK9NZkC4yie7gbrYnm/13UyVmlGiwmXGh6ucCjfSezVbesdY6sFNOWzCxY+NufEvz3k+jC/ljyDzwHbk/nhQ60gdqCs6mbBJ8D4XLN91Lu8hugLNBxUbbgxxdClg3vP59/bghY5PmWOpwNb5G4e0FQYsp7ZBf3OVRZTP1YeIB4FiBpWYWBQ/zPqSLa6gMQrstHzrZ644tSMknAht95XCf6HzWs8Kw7y4/pMMuDoLHhfFs56rsLzenDrMj3ouQ6PNOq2dGIveS7wnTI9CWqsN7O7vn9a8HQ5m3iOtbJ8K7tEKBIn05JXej7yiv+A1Py2R0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
